### ISSUE TITLE
[Suggestion]: Delayed Autohide

### ISSUE THREAD

**Issue by Dannydads** [Fuzss/paperdoll#3]
### Suggestion (Required)

Is there a chance to create a configurable delay on the autohide feature? It would be great if a small timer started up while not moving before it hid itself, so it's not _quite_ there the entire time, but it also doesn't disappear the first moment you stand still.

Thanks, and loving the mod!

**Comment by Fuzss** [comment]
There already is a delay of 750ms. You can configure that with the `display_time` config option.

**Comment by Dannydads** [comment]
Ah... I was apparently running version 1 somehow. It does appear that v8 doesn't work with mod menu though, so I had to go into the client.toml manually. Thnxs

**Comment by Fuzss** [comment]
You can install the Forge Config Screens mod to get Mod Menu to work.
