### ISSUE TITLE
[Suggestion]: The position of the paper doll on screen needs to be customizable. F3+B shows hitboxes on the paper doll.

### ISSUE THREAD

**Issue by WaveSmashies** [Fuzss/paperdoll#4]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

Latest at the moment

### Suggestion (Required)

The paper doll renders slightly under my coordinates which are always on screen thanks to Sodium Extra. I also quite frequently use F3+B to see hitboxes and the hitbox indicator appears on the paper doll lol. It would be nice to have that removed if possible but it makes sense if that's not really fixable.

**Comment by Fuzss** [comment]
You can change the position in the config by choosing a corner and setting a custom offset if necessary.
The hitbox cannot be deactivated, it behaves the same as the vanilla player model in the inventory.
